### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by brendon** [collectiveidea/with_action#2]
This is a great gem. I'm in the process of upgrading to Rails 4.2 and have had a look through the code and can't see any reasons for `with_action` not to work. I was just wondering if this project is still active, in that is there still someone actively responsible for it if it breaks?

**Comment by asheren** [comment]
Hi there! We're doing some open source maintenance work and closing old issues. If this issue is still applicable or you would still like it to be addressed, please re-open the issue by April 17, 2017. Thanks!
